<?php
include('connection/Config.php');
include('connection/Database.php');
include('rest/controllers/MainController.php');
include('rest/controllers/ResponceController.php');
include('rest/controllers/ListController.php');
include('rest/controllers/AbstractController.php');
include('rest/controllers/GetController.php');
include('rest/controllers/EditController.php');
include('rest/models/ListModel.php');
include('rest/models/GetModel.php');
include('rest/models/EditModel.php');